### ISSUE TITLE
Database Issue when using Select command on Dashboard table

### ISSUE THREAD

**Issue by WeirdBalls** [ICT2101-2201-P5-1/CoolMotor#11]
Select queries on the Dashboard Table will result in a time out error.

**Comment by ShawnLemuelDabi** [comment]
Ok. looking into it

**Comment by mayinot** [comment]
@ShawnLemuelDabi  can refer to this issue Database issue when deleting from Levels Table #10. I think they are related.

**Comment by ShawnLemuelDabi** [comment]
@mayinot Yes they are related, I think it is an issue from the Amazons RDS side.

**Comment by ShawnLemuelDabi** [comment]
Hi all, I have re-established the DB. Please do check and let me know if all your functions work properly

Regards,
Shawn
