### ISSUE TITLE
editLevelLayout - code refinement suggestion

### ISSUE THREAD

**Issue by BestCrochet** [ICT2101-2201-P5-1/CoolMotor#12]
Hi @mayinot,

I took a look at your branch after your commit on 15th November.
I have the following comments:

Feature wise:
- for your file path, is it possible to change ../ICT2101/Levels/ to a more relative path? I don't have a folder called ICT2101 and the repo doesn't come with that folder. So when prof pulls the code, he will receive an error.
- For the codes in here, I think you can put them in a for loop to reduce the total lines of code. 
![image](https://user-images.githubusercontent.com/66672755/142383188-d08ec452-d4e5-4dcf-9a57-c93b5ec100fe.png)

You can re-write it to this:
![image](https://user-images.githubusercontent.com/66672755/142383257-64cb70af-7afa-4d68-8397-774f657dbd54.png)

Aesthetic wise:
- I think maybe u can try compressing the 15 coin images / 15 wall  into one image each? The css on my side also has some overlap..

**Comment by mayinot** [comment]
@BestCrochet Please review the latest changes.

**Comment by BestCrochet** [comment]
@mayinot looks good! thanks
