### ISSUE TITLE
Dashboard levels are being regularly emptied

### ISSUE THREAD

**Issue by ShawnLemuelDabi** [ICT2101-2201-P5-1/CoolMotor#16]
Hi guys, facing the issue above. 

Is anyone experimenting with the db? please inform me. thanks and good luck for tomorrow's quiz!😄

**Comment by mayinot** [comment]
Yep! I am facing this issue I cannot view the dashboard page. 
![image](https://user-images.githubusercontent.com/31657679/142746827-528c75c2-8381-4016-ae3a-6b774d57ee93.png)

**Comment by BestCrochet** [comment]
Hi guys, I think this issue is being caused by the foreign key 'map_id' being set to CASCADE. See #10 .
@ShawnLemuelDabi  You may need to change the setting to NO ACTION. 

This will fix the problem, sorry about that!
