### ISSUE TITLE
The canvas element that contians the main game is not centered

### ISSUE THREAD

**Issue by ShawnLemuelDabi** [ICT2101-2201-P5-1/CoolMotor#33]
Tried to fix this using bootstrap and CSS.

Any thoughts? @mayinot @BestCrochet ?

![image](https://user-images.githubusercontent.com/74093668/143669010-8368d0da-1d6b-4ee4-88f2-84f6f84c3e79.png)

**Comment by BestCrochet** [comment]
Hi shawn, i used HTML Canvas and Javascript to make the map. You could try giving the canvas element an ID and configure its CSS from there

**Comment by mayinot** [comment]
I faced the same issues trying to centre the game. I tried using Bootstrap Gird, don't seem to be working well.

**Comment by BestCrochet** [comment]
Hi friends, I just fixed this bug in the latest commit to feature/beautifyIndex , and I also touched up the index page. Made a PR to dev, everything works good now

![image](https://user-images.githubusercontent.com/66672755/143727588-7200e3ce-8081-4fa4-9e3c-4393dc96d3ed.png)
