### ISSUE TITLE
Issues with the Output of the fetchpassword() while using unittest

### ISSUE THREAD

**Issue by ShawnLemuelDabi** [ICT2101-2201-P5-1/CoolMotor#40]
![image](https://user-images.githubusercontent.com/74093668/143770517-a31b6710-134d-4e09-91f6-386200d1200d.png)

**Comment by mayinot** [comment]
this issue can be closed. just remove prepared=True if got database error. remember to remove all these prepared statements during code clean up. might cause an error for prof also
