### ISSUE TITLE
Found hardcoded 'dist_travelled' variable while doing code cleanup

### ISSUE THREAD

**Issue by BestCrochet** [ICT2101-2201-P5-1/CoolMotor#52]
Hi Shawn, 

The variable dist_travelled is still hardcoded under game_processing.js. This value was supposed to be updated after the live dashboard was implemented, could you take a look into it? thanks 😩 !!!!

![image](https://user-images.githubusercontent.com/66672755/144582185-e871a1f8-065b-4744-8f6e-04babd66fddf.png)

**Comment by ShawnLemuelDabi** [comment]
Fixed! Thanks for raising it!
